version: '3.8'

services:
  jenkins-ui:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin
      - SECRET_KEY=your-secret-key-change-this
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./logs:/app/logs
    depends_on:
      - jenkins
    restart: unless-stopped
    networks:
      - jenkins-network

  # Optional: Jenkins server (uncomment if you want to run Jenkins in Docker)
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   environment:
  #     - JENKINS_OPTS=--httpPort=8080
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped
  #   networks:
  #     - jenkins-network

networks:
  jenkins-network:
    driver: bridge

# volumes:
#   jenkins_home: 